dist: xenial

addons:
  apt:
    packages:
      - libyaml-dev

branches:
  only:
  - master

language: c

compiler: gcc

stages:
  - build
  - test

script:
  - make -C hello clean all
  - hello/hello
